/* Utils */
#define WIN_HEIGHT 768
#define WIN_WIDTH 1200
#define HALF_WIN_HEIGHT (WIN_HEIGHT / 2) 
#define HALF_WIN_WIDTH (WIN_WIDTH / 2)
#define MAX_LOOP 100
#define BUFFER_SIZE 5000
#define MAX_DISTANCE_BETWEEN_ENEMIES 500
#define MAX_SHIP_SHOTS 50
#define GRAVITY 9.80665
#define DAMAGE_BY_HITTING_ENEMY 50
#define ENEMY_SHOCK_POWER 10

/* Ship */
#define INITIAL_VELOCITY 30 
#define MOVING_FACTOR 30   
#define VELOCITY_FACTOR 50
#define MAX_XY_ORIENTATION 2000
#define MAX_VELOCITY 2000
#define SHIP_SHOT_NORM 100

/* Enemy */
#define ENEMY_SHOT_VELOCITY 100
#define SHOOTABLE_DISTANCE 400 

